const donorEntries: Array<[string, string]> = [
  ["Chaofang Jin", "chaofangjin@example.com"],
  ["Huijuan Ji", "huijuanji@example.com"],
  ["Jing Xu", "jingxu@example.com"],
  ["Hong Sun", "hongsun@example.com"],
  ["Qinying Lei", "qinyinglei@example.com"],
  ["Baohu Ji", "baohuji@example.com"],
  ["Wenjing Yin", "wenjingyin@example.com"],
  ["Lihpang Lu", "lihpanglu@example.com"],
  ["Wei Wu", "weiwu@example.com"],
  ["Jun Hu", "junhu@example.com"],
  ["Fan Fei", "fanfei@example.com"],
  ["Qingqing Yang", "qingqingyang@example.com"],
  ["Xiao Guan", "xiaoguan@example.com"],
  ["Li Li", "lili@example.com"],
  ["Jingjing Zhang", "jingjingzhang@example.com"],
  ["Qingzhen Guo", "qingzhenguo@example.com"],
  ["Sung Ko", "sungko@example.com"],
  ["Yanru Li", "yanruli@example.com"],
  ["Yu Li", "yuli@example.com"],
  ["Ling Wang", "lingwang@example.com"],
  ["Xin Xu", "xinxu@example.com"],
  ["Yanru Yang", "yanruyang@example.com"],
  ["Honghao Shan", "honghaoshan@example.com"],
  ["Aijie Han", "aijiehan@example.com"],
  ["Tao Liu", "taoliu@example.com"],
  ["Linghan Gao", "linghangao@example.com"],
  ["Yan Wang", "yanwang@example.com"],
  ["Changyi Zhao", "changyizhao@example.com"],
  ["Jing Wu", "jingwu@example.com"],
  ["Haiyun Zhou", "haiyunzhou@example.com"],
  ["Ortal Zeevi", "ortalzeevi@example.com"],
  ["Bo Zhuang", "bozhuang@example.com"],
  ["Yu Shi", "yushi@example.com"],
  ["David Yin", "davidyin@example.com"],
  ["Min Li", "minli@example.com"],
  ["Aurora Xiaoyao Liu", "auroraxiaoyaoliu@example.com"],
  ["Jiacong Li", "jiacongli@example.com"],
  ["Qiao Shen", "qiaoshen@example.com"],
  ["Liang MA", "liangma@example.com"],
  ["Yuping He", "yupinghe@example.com"],
  ["Yongmei Xu", "yongmeixu@example.com"],
  ["Hsiu Lee", "hisulee@example.com"],
  ["Ruoyu Zhang", "ruoyuzhang@example.com"],
];

export const donorDirectory = new Map(donorEntries);
export const donorNames = donorEntries.map(([name]) => name).sort(
  (a, b) => b.length - a.length,
);
